In [12]:
import numpy as np
from numpy.random import default_rng
rng=default_rng(12345)
random_array=rng.random(10).reshape(2,5)
random_array



array([[0.22733602, 0.31675834, 0.79736546, 0.67625467, 0.39110955],
       [0.33281393, 0.59830875, 0.18673419, 0.67275604, 0.94180287]])

In [16]:
random_array[:2]

array([[0.22733602, 0.31675834, 0.79736546, 0.67625467, 0.39110955],
       [0.33281393, 0.59830875, 0.18673419, 0.67275604, 0.94180287]])

In [14]:
random_array[:,0]

array([0.22733602, 0.33281393])

In [18]:
random_array[1,2]

np.float64(0.18673418560371335)

In [19]:
random_array[:,:2]

array([[0.22733602, 0.31675834],
       [0.33281393, 0.59830875]])